@password=20148d3b-e492-4593-9c8f-9c67f604405a
###
GET http://localhost:8080/api/greeting HTTP/1.1
Authorization: Basic user {{password}}

###
POST  http://localhost:8080/api/greeting?name="李寻欢" HTTP/1.1
Authorization: Basic user  {{password}}

###
PUT http://localhost:8080/api/greeting/梁非凡 HTTP/1.1
Authorization: Basic user {{password}}

###
POST http://localhost:8080/api/entityGreeting?name="李寻欢" HTTP/1.1
Authorization: Basic user {{password}}
Content-Type: application/json

{
    "gender":"男",
    "idNo":"01"
}