logging:
  level:
    uaa: DEBUG
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: TRACE
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
              %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
server:
  error:
    whitelabel:
      enabled: true
  port: 8080
  servlet:
    encoding:
      force: true

spring:
  messages:
    basename: messages
    encoding: UTF-8

  datasource:
    #数据库驱动
    driver-class-name: org.h2.Driver
    #数据库密码
    password: ""
    # 数据库连接url，为了兼容mysql，添加;Mode=mysql
    # DATABASE_TO_LOWER = TRUE 是让表名转为小写
    # CASE_INSENSITIVE_INDENTIFIERS=TRUE不区分大小写
    # DB_CLOSE_DELAY=-1 不自动关闭数据库连接
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    # 数据库用户名
    username: sa
    initialization-mode: embedded
  h2:
    console:
      #显示h2嵌入式ui管理界面
      enabled: true
      #访问h2管理界面的路径
      path: /h2-console
      settings:
        #禁止输出Trace信息
        trace: false
        #禁止远程访问h2管理界面
        web-allow-others: false

